### ISSUE TITLE
:100: Update release version

### ISSUE THREAD

**Issue by FelipeFTN** [DioxusLabs/deploy-action#10]
**Hi! Thank you so much for this action, it's very useful!! Just creating this issue because of a tiny bug I found.**

We cannot just copy & paste the sample in the [README.md](https://github.com/DioxusLabs/deploy-action/blob/main/README.md) because the version was not released yet. So, when using this example, it will always generate an error during action execution.

Can you please release a new version `0.1.2` into releases page? :pray: 
```yaml
name: github pages

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: "Dioxus Deploy"
        uses: DioxusLabs/deploy-action@0.1.2
```

<div align="center">

![image](https://github.com/DioxusLabs/deploy-action/assets/80127749/bc78818d-1fa0-458a-bd0f-beb748eb22cb)

</div>
